// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiRiKW53C-hAEdFr_FS0JBxEVal-Zm2gs',
    appId: '1:897226355901:web:124a7c80abe84e0722b3d4',
    messagingSenderId: '897226355901',
    projectId: 'smart-cabinet-3dca8',
    authDomain: 'smart-cabinet-3dca8.firebaseapp.com',
    storageBucket: 'smart-cabinet-3dca8.firebasestorage.app',
    measurementId: 'G-KHZ2LXMTLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBctEZrkWBuzZcLgJ20Ur3ifi-omFcdwyY',
    appId: '1:897226355901:android:8b40aca1579d936622b3d4',
    messagingSenderId: '897226355901',
    projectId: 'smart-cabinet-3dca8',
    storageBucket: 'smart-cabinet-3dca8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBvSxTAQB4zYkowC-zqgd5rcDSjwTgX3E',
    appId: '1:897226355901:ios:44218fce444b228922b3d4',
    messagingSenderId: '897226355901',
    projectId: 'smart-cabinet-3dca8',
    storageBucket: 'smart-cabinet-3dca8.firebasestorage.app',
    iosBundleId: 'com.example.smartCabinet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBvSxTAQB4zYkowC-zqgd5rcDSjwTgX3E',
    appId: '1:897226355901:ios:44218fce444b228922b3d4',
    messagingSenderId: '897226355901',
    projectId: 'smart-cabinet-3dca8',
    storageBucket: 'smart-cabinet-3dca8.firebasestorage.app',
    iosBundleId: 'com.example.smartCabinet',
  );
}
